spring:
    application:
        name: batch-processing
    profiles:
      active: local
logging:
  level:
      org.springframework: INFO
      com..pravinkumbhar: DEBUG  
      
spring.batch.job.enabled : false
   
     